export const segmentConfig = {
  test: 'test',
  item: 'item',
  sub: 'sub',
  home: 'home',
  people: 'people',
  peopleList: 'people-list',
  peopleItem: 'people-item',
  peopleItemAdd: 'people-item-add',
  peopleItemEdit: 'people-item-edit',
  peopleItemShow: 'people-item-show',
  jobPeople: 'job-people',
  jobPeopleList: 'job-people-list',
  jobPeopleItem: 'job-people-item',
  jobPeopleItemAdd: 'job-people-item-add',
  jobPeopleItemEdit: 'job-people-item-edit',
  jobPeopleItemShow: 'job-people-item-show',
  company: 'company',
  companyList: 'company-list',
  companyItem: 'company-item',
  companyItemAdd: 'company-item-add',
  companyItemEdit: 'company-item-edit',
  companyItemShow: 'company-item-show'
};
